### ISSUE TITLE
Deserialization requires all setter-properties to be public, making immutable classes impossible

### ISSUE THREAD

**Issue by Ruslebiffen** [jefffhaynes/BinarySerializer#10]
I just started using this library as it seemed to fit my needs to control the output to a high degree. (I was previously using the Marshal-class).

However, all the objects that I want to serialize and deserialize are immutable, with all the properties set through the constructor. Is there any way to keep them immutable by decorating the parameters of the constructors, or some other way?

**Comment by jefffhaynes** [comment]
Hm, interesting. What happens to them now? (Sorry, not in front of a computer)

**Comment by jefffhaynes** [comment]
Ok I get the gist I think. Let me work on this.

**Comment by Ruslebiffen** [comment]
Guess you got it, but just to make it sure, here is a sample object:
 
    public class MySampleMessage
{
	[FieldOrder(0)]
	public int Id { get; }
	
	[FieldOrder(1)]
	public uint Length { get; }
	
	[FieldOrder(2)]
	public byte[] MessageData { get; }
	
	public MySampleMessage(int id, uint length, byte[] messageData)
	{
		Id = id;
		Length = length;
		MessageData = messageData;
	}
}

In order to successfully deserialize such an object, I need to add public setters for my properties.

**Comment by jefffhaynes** [comment]
Yup, understood. Although in your example you're missing private setters, correct?

**Comment by Ruslebiffen** [comment]
I'm using VS2015 and C# 6, where I guess you no longer need to type out the "private set;" in an auto property. If no setter is defined, it automatically has a private setter. But I changed it for clarity.

**Comment by jefffhaynes** [comment]
Oh, crazy. Ok, thanks!

**Comment by jda808** [comment]
I can confirm as well.

**Comment by jefffhaynes** [comment]
Working on it right now :)

**Comment by jefffhaynes** [comment]
Try using the 4.0 version I just pushed.  Thanks.

**Comment by Ruslebiffen** [comment]
Trying it out now, seems to work good in this case. Good job!

**Comment by jefffhaynes** [comment]
Great, glad to hear it.  Going to close for now, let me know if you have any issues.

**Comment by Ruslebiffen** [comment]
One thing I discovered though, is that it works fine with the example, where the properties are single words like "High" and "Low". However, if you change the property names to "HighNumber" and "LowNumber", and change the constructor parameters to "highNumber" and "lowNumber", you get a TargetParameterCountExcepion: "Parameter Count Mismatch"

**Comment by jefffhaynes** [comment]
That's bizarre...it shouldn't care what the name is.  I'll take a look.

**Comment by jefffhaynes** [comment]
I'm not able to reproduce that.  Can you send me the class definition?  Thanks.

**Comment by Ruslebiffen** [comment]
I edited my previous comment, and added a couple cases that causes this exception to be thrown.

**Comment by jefffhaynes** [comment]
Got it, I screwed up my test.

**Comment by jefffhaynes** [comment]
ok, fixed in 4.0.1, thanks

**Comment by Ruslebiffen** [comment]
It doesn't seem to fix the problem for me. Here is the code I use to test the serialization and deserialization:

    var serializer = new BinarySerializer();
    var longAddress = new LongAddress(100, 100);

    byte[] serialized;

    // Serialize object to byte array
    using (var stream = new MemoryStream())
    {
           serializer.Serialize(stream, longAddress);
           serialized = stream.ToArray();
    }

    // Deserialize byte array back to an object
    var deserialized = serializer.Deserialize<LongAddress>(serialized);

StackTrace:

    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
    at BinarySerialization.Graph.ValueGraph.ObjectValueNode.get_Value()
    at BinarySerialization.Graph.ValueGraph.ContextValueNode.get_Value()
    at BinarySerialization.BinarySerializer.Deserialize[T](Stream stream, Object context)
    at BinarySerialization.BinarySerializer.Deserialize[T](Byte[] data, Object context)
    at SerializerTests.SerializeAndDeserializeImmutable() in D:\...\SerializerTests.cs:line 57

**Comment by jefffhaynes** [comment]
Ok, I'll have to look at it tonight.

**Comment by Ruslebiffen** [comment]
Just an update. I cloned your project to my machine, and it works fine in the first scenario. However, not with nullable parameters. 

In `SubTypeInfo.cs`, it finds the constructor, and sets `Constructor = bestConstructor.Constructor;`
However, the result in `bestConstructor.ParameterMap` is empty. So there seems to be something that goes wrong in the join, when a parameter is nullable.

**Comment by jda808** [comment]
If you remove the "using" block, does it yield different results?

**Comment by jefffhaynes** [comment]
Yeah, this actually goes back to a fundamental thing I did in the base type node, which I've never been happy with.  I went back and refactored it and hopefully it's good now.  Just pushed 4.0.2, let me know.  Thanks.

**Comment by Ruslebiffen** [comment]
Great job, everything is working good now. Props for being so quick to add support for this.

**Comment by jefffhaynes** [comment]
Lol damn I thought I handled that case. Ok, back to the drawing board...

**Comment by jefffhaynes** [comment]
I looked at this again and I'm not entirely sure I understand.  By marking the ReponseId as Ignored, you're telling the serializer not to deserialize that field.  But if the field isn't being deserialized then it isn't available during construction.  I'm not sure what the appropriate behavior should be.

Anyway, you're right that there was a bug since you should have been able to just add the single parameter constructor and have it work.  It's fixed in 4.0.3.

**Comment by jefffhaynes** [comment]
I'm going to close this for now.  Let me know if you're still having issues, thanks.
