### ISSUE TITLE
BinarySerializer with Windows Phone 8.1

### ISSUE THREAD

**Issue by abrasat** [jefffhaynes/BinarySerializer#11]
I am getting a compatibility error message when I try to install the BinarySerializer package in a WindowsPhone 8.1 project. Should a PCL (portable) class library not work also for WinPhone 8.1 ?

**Comment by jefffhaynes** [comment]
The library is currently on PCL profile 78.  I'll update to 344, which should work.

**Comment by abrasat** [comment]
I tried to update by myself the profile to 344, but now I get a runtime error (during deserialization) on Windows Phone 8.1: 

Could not load file or assembly 'System.Runtime.Serialization, ..."

It looks like this is not available on Windows Phone.

**Comment by jefffhaynes** [comment]
Hm, I'm not sure why it would need that assembly.  I'll try to take a look tonight.

**Comment by jefffhaynes** [comment]
Try using 4.0, which I just pushed.  It seemed to work for me.

**Comment by jefffhaynes** [comment]
Can you confirm this is working?

**Comment by abrasat** [comment]
Sorry for the late answer, I could test it only today. I still get the same exception in TypeNode.cs, row number 82 (var attributes = memberInfo.GetCustomAttributes(true);)

System.IO.FileNotFoundException could not load file or assembly
  HResult=-2147024894
Message=Could not load file or assembly 'System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
  Source=mscorlib
  FileName=System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  StackTrace:
       at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
       at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
       at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
       at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
       at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean isDecoratedTargetSecurityTransparent)
       at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo property, RuntimeType caType)
       at System.Reflection.RuntimePropertyInfo.GetCustomAttributes(Boolean inherit)
       at BinarySerialization.Graph.TypeGraph.TypeNode..ctor(TypeNode parent, Type parentType, MemberInfo memberInfo)
       at BinarySerialization.Graph.TypeGraph.ValueTypeNode..ctor(TypeNode parent, Type parentType, MemberInfo memberInfo)
  InnerException:

**Comment by jefffhaynes** [comment]
Can you post what you're trying to serialize?  Thanks.

**Comment by abrasat** [comment]
Actually the class I am trying to serialize contains besides the BinarySerializer specific annotations also annotations for XML serialization. Could that be a problem when running BinarySerializer on Windows Phone ?

    [DataContract]
    public class MyData
    {
        [FieldOrder(0)]
        [DataMember]
        public int Level { get; set; }

        [FieldOrder(1)]
        [FieldLength(32)]
        [DataMember]
        public string Name { get; set; }

        [FieldOrder(2)]
        [FieldLength(48)]
        [DataMember]
        public string Function { get; set; }
....

**Comment by jefffhaynes** [comment]
Yes, that would be my guess.  When the serializer goes to construct the class those attributes won't get resolved without the serialization binary.  Try removing them if you can and see what happens.

**Comment by abrasat** [comment]
Unfortunately I cannot test the Windows Phone application today anymore, I will give you the feedback on monday.
Is it not possible to ignore the "not BinarySerializer"-attributes ?

**Comment by jefffhaynes** [comment]
Unfortunately it's not a matter of ignoring them.  When I go to construct the type, the CLR is going to try to resolve those assemblies.  I believe I could intercept the assembly loads from the app domain but then I wouldn't really have any recourse since I can't construct those types without the serializer assembly.

I will say, in my experience (having done similar things several times myself), it may be your best bet to decouple the two types of serialization.  While it's tempting to want to have a single definition for everything, inevitably there turn out to be differences in the serializers or application (probably like this) that make it all end in tears :)

**Comment by jefffhaynes** [comment]
I'm going to close this for now.  Let me know if you're still having trouble with it.
