### ISSUE TITLE
Bitfields serialization is counterintuitive to C bitfields

### ISSUE THREAD

**Issue by moonshadow565** [jefffhaynes/BinarySerializer#122]
Considering the following example of BinarySerializer's bitfield struct:
```
public class Foo
{
    [FieldOrder(0)]
    [FieldBitLength(4)]
    public byte X { get; set; } = 0x01;

    [FieldOrder(1)]
    [FieldBitLength(4)]
    public byte Y { get; set; } = 0x02;
}
```
Which would be equivalent of the following C bitfield:
```
struct Foo {
   uint8_t X : 4 = 0x01;
   uint8_t Y : 4 = 0x02;
}; 
```
Serializer produces the value `0x12` while the C variant produces `0x21`.
I would expect the default behavior to be same as C bitfield.
Further more C-like serialization should be much easier to write than the current one.

**Comment by jefffhaynes** [comment]
Can you clarify what you mean?  In what way are they counterintuitive?


________________________________

**Comment by moonshadow565** [comment]
I assume you are replaying from email because i edited the message to provide example (accidentally hit enter key).

**Comment by moonshadow565** [comment]
This fixes the issue for me but changes how bitfields work overall:
https://github.com/jefffhaynes/BinarySerializer/compare/master...moonshadow565:bitfield#diff-11cb5a548dbf144e09274b952be811f5

**Comment by jefffhaynes** [comment]
That is somewhat unfortunate...I’m reluctant to make a breaking change to the framework, although it is a relatively new feature. 

Another option is to introduce a bit ordering attribute or something.

**Comment by microtronics** [comment]
This threw my code off as well. Moreover it appears that Endianess is reversed for bitfields. It looks like Serialization always makes bitfields Big-Endian.

**Comment by jefffhaynes** [comment]
Ok sorry about that. I’ll try to look at this tomorrow


________________________________

**Comment by jefffhaynes** [comment]
After further consideration I decided this is simply a bug.  I think it's fixed in 8.4 but please try it out and let me know how it works.  Thanks

**Comment by jefffhaynes** [comment]
Er, hold on...hit some deployment issue

**Comment by microtronics** [comment]
Yep. I just tried it and the problem persists. Thanks for working on it, though!

**Comment by jefffhaynes** [comment]
Sorry about that - please try 8.4.1

**Comment by microtronics** [comment]
There are still issues:

`
var p = new LaserFrame
            {
                X = 0x123,
                Y = 0x456,
                R = 0x78,
                G = 0x90,
                B = 0xAB
            };
var mem = new MemoryStream(10);
var ser = new BinarySerializer();
ser.Serialize(mem, p);
var serArr = mem.ToArray();
`

LaserFrame:
`
    class LaserFrame
    {
        [FieldEndianness(Endianness.Little)]
        [FieldOrder(0)]
        [FieldBitLength(12)]
        public uint X { get; set; }
        [FieldEndianness(Endianness.Little)]
        [FieldOrder(1)]
        [FieldBitLength(12)]
        public uint Y { get; set; }
        [FieldOrder(2)]
        public byte R { get; set; }
        [FieldOrder(3)]
        public byte G { get; set; }
        [FieldOrder(4)]
        public byte B { get; set; }
    }
`

Should deliver 0x23 0x61 0x45 0x78 0x90 0xAB. However the 0x5 is missing. Moreover, setting it to Big-Endian completely omits the bitfields.

**Comment by moonshadow565** [comment]
You might reconsider adding a new attribute for bitfields like this.
C implementations of  bitfields  also usually do sign extension for signed numbers.

**Comment by jefffhaynes** [comment]
Unfortunately I haven’t had time to fix it yet but is there a reason to add a new attribute versus simply fixing the behavior?


________________________________

**Comment by jefffhaynes** [comment]
Thanks for the example.  I rewrote the bit field handling and I feel much better about it now but let me know if you still have issues.  I haven't tackled big endian yet but I figured I would push what I have so far (in 8.4.2).  If you have a big endian example, please post it so I have something to test against.  Thanks

**Comment by briggsj** [comment]
Jeff, 
Unfortunately this "fix" breaks the the interface I'm working on. Using the OPs example: 
``` c#
struct Foo {
   uint8_t X : 4 = 0x01;
   uint8_t Y : 4 = 0x02;
}
```
The hardware I'm interfacing with expects this to be 0x12 like it was previous to [this](https://github.com/jefffhaynes/BinarySerializer/commit/54c29e5d12cb73f52279fcb5bf53abd28c5fc1af). This is working for us now but I thought you should know your previous implementation did have a use.

**Comment by jefffhaynes** [comment]
Sorry about that. I know breaking changes are reprehensible but I figured in this case it was better to bite the bullet and take the hit sooner rather than later. Sorry that you had to bear the brunt of it. Glad it's working now.
